Moved to UI Kit release 3.1.0.0
syncfusion/essential-ui-kit-for-xamarin.forms pull request #48
Opened 2020-05-15 13:16 UTC by MohanlalGo

2020-08-10 16:24 UTC, stephenhauck commented
Anyone .. hello ?

2020-09-03 20:13 UTC, phungdkh commented
Greate templates to start a new project
Thanks to every one

2020-12-12 17:37 UTC, Kevin277v approved these changes

2020-12-12 17:39 UTC, Kevin277v requested changes
https://github.com/syncfusion/essential-ui-kit-for-xamarin.forms/pull/48[]()

2021-03-31 17:26 UTC, closed without merging